const PDFDocument = require('pdfkit');

const formatMoney = (n) => {
  const num = Number(n || 0);
  return num.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

const formatDate = (d) => {
  if (!d) return '—';
  try {
    return new Date(d).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: '2-digit' });
  } catch {
    return '—';
  }
};

const durationLabelFromData = (durationType, totalDays) => {
  const type = String(durationType || '').toLowerCase();
  const label = type === 'yearly' ? 'Yearly' : type === 'monthly' ? 'Monthly' : 'Custom';
  return `${label} (${Number(totalDays || 0)} days)`;
};

/**
 * Builds a professional subscription receipt PDF without Chrome/Puppeteer
 * (works on Vercel serverless and standard Node hosts).
 */
const generateReceiptPdf = (data) =>
  new Promise((resolve, reject) => {
    const {
      businessName,
      receiptId,
      clientName,
      clientWhatsApp,
      clientEmail,
      subscriptionName,
      durationLabel,
      startDate,
      endDate,
      sellingPrice,
      paymentStatus,
      profit,
    } = data;

    const doc = new PDFDocument({
      size: 'A4',
      margin: 40,
      info: { Title: 'Subscription Receipt', Creator: 'ManageMySubs' },
    });

    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageW = doc.page.width;
    const margin = 40;
    const contentW = pageW - margin * 2;
    const primary = '#4f46e5';
    const accent = '#06b6d4';
    const muted = '#64748b';
    const border = '#e2e8f0';
    const dark = '#0f172a';

    // --- Header band (gradient-style: two-tone strip) ---
    doc.save();
    try {
      const g = doc.linearGradient(0, 0, pageW, 0);
      g.stop(0, primary).stop(1, accent);
      doc.rect(0, 0, pageW, 108).fill(g);
    } catch {
      doc.rect(0, 0, pageW, 108).fill(primary);
    }
    doc.restore();

    doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(20).text(String(businessName || 'Your Business'), margin, 32, {
      width: contentW - 130,
    });
    doc.font('Helvetica').fontSize(9).text('SUBSCRIPTION RECEIPT', margin, 58);
    doc.font('Helvetica-Bold').fontSize(13).text(String(subscriptionName || 'Subscription'), margin, 72);
    doc
      .fillColor('#e0e7ff')
      .font('Helvetica-Bold')
      .fontSize(9)
      .text(`Receipt #${receiptId || '—'}`, margin, 42, { width: contentW, align: 'right' });

    let y = 128;

    const drawSectionTitle = (x, yy, title) => {
      doc.fillColor(muted).font('Helvetica-Bold').fontSize(8).text(title.toUpperCase(), x, yy);
    };

    const drawKV = (x, yy, label, value, maxW) => {
      doc.fillColor(muted).font('Helvetica').fontSize(9).text(label, x, yy, { width: 90 });
      doc.fillColor(dark).font('Helvetica-Bold').fontSize(10).text(String(value || '—'), x + 92, yy, {
        width: maxW - 92,
        align: 'left',
      });
    };

    const gap = 14;
    const colW = (contentW - gap) / 2;
    const boxH = 108;

    // Client + Subscription columns
    doc.roundedRect(margin, y, colW, boxH, 10).stroke(border);
    drawSectionTitle(margin + 12, y + 12, 'Client info');
    drawKV(margin + 12, y + 30, 'Name', clientName, colW - 24);
    drawKV(margin + 12, y + 48, 'WhatsApp', clientWhatsApp, colW - 24);
    drawKV(margin + 12, y + 66, 'Email', clientEmail, colW - 24);

    const x2 = margin + colW + gap;
    doc.roundedRect(x2, y, colW, boxH, 10).stroke(border);
    drawSectionTitle(x2 + 12, y + 12, 'Subscription info');
    const dur = durationLabel || durationLabelFromData(data.durationType, data.totalDays);
    drawKV(x2 + 12, y + 30, 'Duration', dur, colW - 24);
    drawKV(x2 + 12, y + 48, 'Start date', formatDate(startDate), colW - 24);
    drawKV(x2 + 12, y + 66, 'End date', formatDate(endDate), colW - 24);

    y += boxH + gap;

    // Payment block (full width)
    const payH = 120;
    doc.roundedRect(margin, y, contentW, payH, 10).stroke(border);
    doc.rect(margin, y, contentW, 28).fill('#f8fafc');
    doc.fillColor(muted).font('Helvetica-Bold').fontSize(8).text('PAYMENT', margin + 12, y + 10);

    const status = String(paymentStatus || 'pending');
    doc.fillColor(dark).font('Helvetica-Bold').fontSize(11).text(`Status: ${status}`, margin + 12, y + 38);
    doc.fillColor(muted).font('Helvetica').fontSize(9).text('Selling price', margin + 12, y + 58);
    doc.fillColor(primary).font('Helvetica-Bold').fontSize(22).text(formatMoney(sellingPrice), margin + 12, y + 72);
    doc.fillColor(muted).font('Helvetica').fontSize(9).text(`Profit (realized): ${formatMoney(profit)}`, margin + 12, y + 98);

    doc
      .fillColor(muted)
      .font('Helvetica')
      .fontSize(8)
      .text('Thank you — receipt generated by ManageMySubs. Keep for your records.', margin + 220, y + 42, {
        width: contentW - 232,
        lineGap: 2,
      });

    y += payH + 24;

    doc
      .fillColor(muted)
      .font('Helvetica')
      .fontSize(8)
      .text(`Generated at ${new Date().toLocaleString()}`, margin, y, { width: contentW / 2 });
    doc.fillColor(primary).font('Helvetica-Bold').text('ManageMySubs', margin + contentW / 2, y, {
      width: contentW / 2,
      align: 'right',
    });

    doc.end();
  });

module.exports = { generateReceiptPdf };
